version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip..."
      - python -m pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running Django checks..."
      - python manage.py check --fail-level WARNING
  build:
    commands:
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput
      - echo "Running migrations..."
      - python manage.py migrate --noinput --verbosity 2
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '/*'
  exclude-paths:
    - '/.git/'
    - 'venv/'
    - '/*.pyc'
    - '/_pycache_/'
    - '/db.sqlite3/'