# Generated by Django 5.1.7 on 2025-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
